worker_processes auto;

events {
    worker_connections 1024;
}

stream {
    upstream backend_http {
        server nginx_01:80 max_fails=3 fail_timeout=5s;
        server nginx_02:80 max_fails=3 fail_timeout=5s;
    }

    upstream backend_https {
        server nginx_01:443 max_fails=3 fail_timeout=5s;
        server nginx_02:443 max_fails=3 fail_timeout=5s;
    }

    server {
        listen 80;
        proxy_pass backend_http;
    }

    server {
        listen 443;
        proxy_pass backend_https;
    }
}
