# nginx.conf

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # O teu bloco de servidores corrigido entra aqui dentro:
    upstream backend_chat {
        # O NGINX vai fazer round-robin entre os dois containers
        server neo_chat_01:3000;
        server neo_chat_02:3000;
    }

    server {
        listen 80;
        server_name chat.local;
        # Redireciona todo o tráfego HTTP para HTTPS automaticamente
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name chat.local;

        # Caminho dos certificados dentro do container
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        # Melhores práticas de segurança para SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Envia os headers necessários para o Authelia
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-URI $request_uri;
        proxy_set_header X-Forwarded-Ssl on;
        
        # A aplicação principal de chat
        location = /ipca-chat {
            return 301 /ipca-chat/;
        }

        location /ipca-chat/ {
            proxy_pass http://backend_chat/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # Rotas necessárias pelo Vite e pelo Server Node
        location /chat-api/ {
            proxy_pass http://backend_chat/chat-api/;
        }

        location /assets/ {
            proxy_pass http://backend_chat/assets/;
        }

        location /socket.io/ {
            proxy_pass http://backend_chat/socket.io/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
        
        location / {
            proxy_pass http://authelia:9091; 
        }
    }
}