# configuration.yml

theme: light

server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: 'info'

# Correção do aviso: Nova estrutura para o segredo do JWT
identity_validation:
  reset_password:
    jwt_secret: 'um_secret_temporario_de_trinta_e_dois_bits_minimo'

authentication_backend:
  password_reset:
    disable: true
  file:
    path: '/config/users_database.yml'

access_control:
  default_policy: 'one_factor'

# Correção dos Erros Fatais: Domínio IP, HTTPS obrigatório e redirecionamento interno
session:
  name: 'authelia_session'
  secret: 'outro_secret_de_trinta_e_dois_caracteres_minimo'
  cookies:
    - domain: 'chat.local'
      authelia_url: 'https://chat.local'
      default_redirection_url: 'https://chat.local/ipca-chat/'

# Correção do aviso: Nova sintaxe 'address' unificada com tcp://
storage:
  encryption_key: 'chave_de_encriptacao_de_trinta_e_dois_caracteres'
  postgres:
    address: 'tcp://pgpool_balancer:5432'
    database: 'authelia_db'
    username: 'chat_admin'
    password: 'senha_secreta'

notifier:
  filesystem:
    filename: '/config/notification.txt'